On row 3, column "a_dataset_uuid", value "bad" fails because URL returned 404: "https://portal.hubmapconsortium.org/browse/dataset/bad"
On row 4, column "a_full_url", value "https://portal.hubmapconsortium.org/bad" fails because URL returned 404: "https://portal.hubmapconsortium.org/bad"
