>>> print_messages()
Traceback (most recent call last):
...
FileNotFoundError: [Errno 2] No such file or directory: 'tests/fixtures/bad-missing-data/submission/dataset-1'
